export const HYDERABAD_AREAS = [
  "Banjara Hills",
  "Jubilee Hills",
  "Madhapur",
  "Gachibowli",
  "Kondapur",
  "Hitech City",
  "Manikonda",
  "Kukatpally",
  "Miyapur",
  "KPHB Colony",
  "Moosapet",
  "Bowenpally",
  "Balapur",
  "Chandrayanagutta",
  "Charminar",
  "Dilsukhnagar",
  "ECIL",
  "Falaknuma",
  "Golconda",
  "Habsiguda",
  "Himayatnagar",
  "Hyderguda",
  "Kachiguda",
  "Koti",
  "Lakdi Ka Pul",
  "Langer House",
  "Malkajgiri",
  "Mallapur",
  "Masab Tank",
  "Nampally",
  "Narayanguda",
  "Punjagutta",
  "Ramanthapur",
  "Safilguda",
  "Sainikpuri",
  "Sanathnagar",
  "Secunderabad",
  "Sriram Nagar",
  "Tarnaka",
  "Tolichowki",
  "Uppal",
  "Vanasthalipuram",
  "Yapral",
];

export const AREA_GROUPS = [
  { label: "West Hyderabad", areas: ["Banjara Hills", "Jubilee Hills", "Madhapur", "Gachibowli", "Kondapur", "Hitech City", "Manikonda"] },
  { label: "North Hyderabad", areas: ["Kukatpally", "Miyapur", "KPHB Colony", "Moosapet", "Bowenpally", "Balapur", "Chandrayanagutta"] },
  { label: "East Hyderabad", areas: ["ECIL", "Habsiguda", "Malkajgiri", "Mallapur", "Safilguda", "Sainikpuri", "Uppal", "Yapral"] },
  { label: "South Hyderabad", areas: ["Charminar", "Dilsukhnagar", "Falaknuma", "Golconda", "Langer House", "Tolichowki", "Vanasthalipuram"] },
  { label: "Central Hyderabad", areas: ["Himayatnagar", "Hyderguda", "Kachiguda", "Koti", "Lakdi Ka Pul", "Masab Tank", "Nampally", "Narayanguda", "Punjagutta", "Ramanthapur", "Sanathnagar", "Secunderabad", "Sriram Nagar", "Tarnaka"] },
];
